customhost = "rds-endpoint"
customuser = "database username"
custompass = "database password"
customdb = "employee"
custombucket = "s3-bucket-name"
customregion = "region where your s3-bucket is located"
